export { default as Bar } from './Bar.vue'
export { default as Line } from './Line.vue'
export { default as Donut } from './Donut.vue'
export { default as Pie } from './Pie.vue'
export { default as Area } from './Area.vue'
